// src/pages/NewOrderPage.tsx - UPDATED FOR DUPLICATION

import React, { useState, useCallback, useMemo, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom"; // Added useLocation
import { useQueryClient } from "@tanstack/react-query";
import { createOrder } from '../services/orderService';
import { Order, OrderStatus } from '../types/index';
import { queryKeys } from '../constants/queryKeys';
import OrderForm, { SaveData } from '../components/orders/OrderForm';
import { useWarnIfUnsaved } from "../hooks";
import UnsavedChangesModal from "../components/ui/UnsavedChangesModal";
import { useAuth } from "../contexts/AuthContext";
import { Copy } from "lucide-react";

const NewOrderPage: React.FC = () => {
  const [isSaving, setIsSaving] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [isDirty, setIsDirty] = useState(false);
  const [navigateTo, setNavigateTo] = useState<string | null>(null); // NEW: For synchronized navigation
  const [allowNavigation, setAllowNavigation] = useState(false); // NEW: For navigation shield
  
  const navigate = useNavigate();
  const location = useLocation(); // Hook to get the passed data
  const queryClient = useQueryClient();
  const { user } = useAuth();
  
  const { showModal, confirmLeave, cancelLeave } = useWarnIfUnsaved(isDirty, allowNavigation);

  // This effect ensures navigation only happens after the state is clean.
  useEffect(() => {
    if (navigateTo && allowNavigation) {
      navigate(navigateTo);
    }
  }, [navigateTo, allowNavigation, navigate]);


  // --- DUPLICATION LOGIC ---
  // Check if we were sent here with an order to duplicate
  const sourceOrder = location.state?.duplicateOrder as Order | undefined;

  const initialData = useMemo(() => {
    if (!sourceOrder) return null;

    // We strip out unique identifiers so it creates a NEW entry
    return {
      ...sourceOrder,
      id: 0, // Reset ID
      orderNumber: '', // Will be generated by DB
      status: OrderStatus.NEW_ORDER, // Reset Status
      createdAt: '', // Reset Date
      updatedAt: '',
      
      // Reset Shipping Specifics (usually different for new orders)
      shippingTrackingNumber: '',
      
      // Reset Financials (Calculated automatically by form)
      amountPaid: 0,
      
      // KEEP: Customer info, Design info, File URLs (Mockups/Production files are reusable for repeats)
    } as Order;
  }, [sourceOrder]);

  const handleSave = async (formData: SaveData) => {
    setIsSaving(true);
    setError(null);
    
    try {
      // --- CRITICAL MAPPING: CAMELCASE -> SNAKE_CASE ---
      const dbPayload = {
        customer_name: formData.customerName,
        customer_email: formData.customerEmail,
        customer_phone: formData.customerPhone,
        customer_profile_url: formData.customerProfileUrl,
        
        shipping_address: formData.shippingAddress,
        shipping_carrier: formData.shippingCarrier,
        shipping_tracking_number: formData.shippingTrackingNumber,
        
        design_name: formData.designName,
        patches_quantity: formData.patchesQuantity,
        patches_type: formData.patchesType,
        design_size: formData.designSize,
        design_backing: formData.designBacking,
        instructions: formData.instructions,
        
        // ✅ FIX: Ensure order_amount is never null, defaulting to 0.
        // This prevents the NOT NULL constraint violation for roles that can't see financials.
        order_amount: formData.orderAmount ?? 0,
        
        // *** THIS IS THE FIX ***
        amount_paid: formData.amountPaid, 
        
        production_cost: formData.productionCost || 0,
        shipping_cost: formData.shippingCost || 0,
        marketing_cost: formData.marketingCost || 0,

        lead_source: formData.leadSource,
        status: formData.status.toString(),
        is_urgent: formData.isUrgent,
        
        // Arrays
        mockup_urls: formData.mockupUrls,
        production_file_urls: formData.productionFileUrls,
        shipping_attachment_urls: formData.shippingAttachmentUrls,
        customer_attachment_urls: formData.customerAttachmentUrls
      };

      // Send the mapped payload (dbPayload), NOT formData
      const newOrder = await createOrder(dbPayload, user?.email || 'unknown');
      
      // ✅ SUCCESS SEQUENCE
      // 1. Invalidate queries to start refetching data in the background.
      await queryClient.invalidateQueries({ queryKey: queryKeys.orders.all() });
      await queryClient.invalidateQueries({ queryKey: queryKeys.dashboard.table('', '') });

      // 2. Set the state to allow navigation and define the destination path.
      setAllowNavigation(true);
      setIsDirty(false);
      // ✅ FIX: Use state to navigate, preventing a race condition with the unsaved changes modal.
      setNavigateTo(`/order/${newOrder.orderNumber}/edit`);
      
    } catch (err: any) {
      console.error('Failed to create order', err);
      // ✅ FIX: Properly handle different error shapes.
      // Supabase errors are objects with a 'message' property. Other errors might be strings or standard Error objects.
      const errorMessage = err?.message || (typeof err === 'string' ? err : 'An unknown error occurred. Check the console for details.');
      setError(`Failed to create order: ${errorMessage}`);
      setIsDirty(true);
    } finally {
      // ✅ Always stop the spinner, whether the save succeeded or failed.
      // This ensures the UI is responsive and allows navigation to proceed.
      setIsSaving(false);
    }
  };

  const onFormChange = useCallback(() => {
    if (isSaving) return; // 🛡️ SHIELD: If we are saving, ignore changes.
    if (!isDirty) {
      setIsDirty(true);
      setAllowNavigation(false); // Re-engage the shield if user makes more changes
    }
  }, [isDirty, isSaving]);

  return (
    <div className="p-6 max-w-7xl mx-auto">
      <div className="mb-6">
        <h2 className="text-3xl font-bold text-white flex items-center gap-3">
          {sourceOrder ? (
            <>
              <Copy className="w-8 h-8 text-blue-400" />
              <span>Repeat Order <span className="text-slate-500 text-lg font-normal">(Copying {sourceOrder.orderNumber})</span></span>
            </>
          ) : (
            "Create New Order"
          )}
        </h2>
        {sourceOrder && (
            <p className="text-slate-400 mt-1 ml-11">
                Details from the previous order have been pre-filled. Please review quantities and costs.
            </p>
        )}
      </div>
      
      <UnsavedChangesModal 
        show={showModal}
        onConfirm={confirmLeave}
        onCancel={cancelLeave}
      />
      
      {error && (
        <div className="mb-6 p-4 bg-red-500/10 border-l-4 border-red-500 text-red-300 rounded-r-lg">
          <h3 className="font-bold">Error</h3>
          <p>{error}</p>
        </div>
      )}
      
      {/* Pass the sanitized 'initialData' to the form to pre-fill it */}
      <OrderForm 
        onSave={handleSave} 
        isSaving={isSaving} 
        onFormChange={onFormChange} 
        initialData={initialData} 
        isNewOrder={true}
      />
    </div>
  );
};

export default NewOrderPage;