// src/pages/NewOrderPage.tsx - UPDATED FOR DUPLICATION

import React, { useState, useCallback, useMemo } from "react";
import { useNavigate, useLocation } from "react-router-dom"; // Added useLocation
import { useQueryClient } from "@tanstack/react-query";
import { createOrder } from '../services/orderService';
import { Order, OrderStatus } from '../types/index';
import OrderForm, { SaveData } from '../components/orders/OrderForm';
import { useWarnIfUnsaved } from "../hooks";
import UnsavedChangesModal from "../components/ui/UnsavedChangesModal";
import { useAuth } from "../contexts/AuthContext";
import { Copy } from "lucide-react";

const NewOrderPage: React.FC = () => {
  const [isSaving, setIsSaving] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [isDirty, setIsDirty] = useState(false);
  
  const navigate = useNavigate();
  const location = useLocation(); // Hook to get the passed data
  const queryClient = useQueryClient();
  const { user } = useAuth();
  
  const { showModal, confirmLeave, cancelLeave } = useWarnIfUnsaved(isDirty);

  // --- DUPLICATION LOGIC ---
  // Check if we were sent here with an order to duplicate
  const sourceOrder = location.state?.duplicateOrder as Order | undefined;

  const initialData = useMemo(() => {
    if (!sourceOrder) return null;

    // We strip out unique identifiers so it creates a NEW entry
    return {
      ...sourceOrder,
      id: 0, // Reset ID
      orderNumber: '', // Will be generated by DB
      status: OrderStatus.NEW_ORDER, // Reset Status
      createdAt: '', // Reset Date
      updatedAt: '',
      
      // Reset Shipping Specifics (usually different for new orders)
      shippingTrackingNumber: '',
      
      // Reset Financials (Calculated automatically by form)
      amountPaid: 0,
      
      // KEEP: Customer info, Design info, File URLs (Mockups/Production files are reusable for repeats)
    } as Order;
  }, [sourceOrder]);

  const handleSave = async (formData: SaveData) => {
    const productionCost = Number(formData.productionCost) || 0;
    const shippingCost = Number(formData.shippingCost) || 0;
    const marketingCost = Number(formData.marketingCost) || 0;
    const orderAmount = Number(formData.orderAmount) || 0;
    const profit = orderAmount - (productionCost + shippingCost + marketingCost);

    setIsSaving(true);
    setError(null);
    
    try {
      // We map the SaveData back to what createOrder expects
      const payload = {
          ...formData,
          profit,
          // Ensure status is string for DB
          status: formData.status.toString() 
      };

      const newOrder = await createOrder(payload, user?.email || 'unknown');
      
      // Success!
      setIsDirty(false);
      await queryClient.invalidateQueries({ queryKey: ['allOrders'] });
      await queryClient.invalidateQueries({ queryKey: ['dashboard-orders'] });
      navigate(`/order/${newOrder.orderNumber}`);
      
    } catch (err: any) {
      console.error('Failed to create order', err);
      setError(`Failed to create order: ${err.message || 'An unknown error occurred.'}`);
      setIsDirty(true); // Keep dirty so they don't lose data
    } finally {
      setIsSaving(false);
    }
  };

  const onFormChange = useCallback(() => {
    if (!isDirty) setIsDirty(true);
  }, [isDirty]);

  return (
    <div className="p-6 max-w-7xl mx-auto">
      <div className="mb-6">
        <h2 className="text-3xl font-bold text-white flex items-center gap-3">
          {sourceOrder ? (
            <>
              <Copy className="w-8 h-8 text-blue-400" />
              <span>Repeat Order <span className="text-slate-500 text-lg font-normal">(Copying {sourceOrder.orderNumber})</span></span>
            </>
          ) : (
            "Create New Order"
          )}
        </h2>
        {sourceOrder && (
            <p className="text-slate-400 mt-1 ml-11">
                Details from the previous order have been pre-filled. Please review quantities and costs.
            </p>
        )}
      </div>
      
      <UnsavedChangesModal 
        show={showModal}
        onConfirm={confirmLeave}
        onCancel={cancelLeave}
      />
      
      {error && (
        <div className="mb-6 p-4 bg-red-500/10 border-l-4 border-red-500 text-red-300 rounded-r-lg">
          <h3 className="font-bold">Error</h3>
          <p>{error}</p>
        </div>
      )}
      
      {/* Pass the sanitized 'initialData' to the form to pre-fill it */}
      <OrderForm 
        onSave={handleSave} 
        isSaving={isSaving} 
        onFormChange={onFormChange} 
        initialData={initialData} 
      />
    </div>
  );
};

export default NewOrderPage;