// src/pages/NewOrderPage.tsx - UPDATED FOR DUPLICATION

import React, { useState, useEffect, useMemo, useCallback } from "react";
import { useNavigate, useLocation } from "react-router-dom"; // Added useLocation
import { useQueryClient } from "@tanstack/react-query";
import { createOrder } from '../services/orderService';
import { Order, OrderStatus } from '../types/index';
import { queryKeys } from '../constants/queryKeys';
import OrderForm, { SaveData } from '../components/orders/OrderForm';
import { useWarnIfUnsaved } from "../hooks";
import UnsavedChangesModal from "../components/ui/UnsavedChangesModal";
import { useAuth } from "../contexts/AuthContext";
import { useToast } from "../hooks/useToast";
import { logger } from "../services/logger";
import { Copy } from "lucide-react";

const NewOrderPage: React.FC = () => {
  const [isSaving, setIsSaving] = React.useState<boolean>(false);
  const [error, setError] = React.useState<string | null>(null);
  const [isDirty, setIsDirty] = React.useState(false);
  const [navigateTo, setNavigateTo] = React.useState<string | null>(null); // NEW: For synchronized navigation
  const [allowNavigation, setAllowNavigation] = React.useState(false); // NEW: For navigation shield
  
  const navigate = useNavigate();
  const location = useLocation(); // Hook to get the passed data
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const { success: showSuccess } = useToast();
  
  const { showModal, confirmLeave, cancelLeave } = useWarnIfUnsaved(isDirty, allowNavigation);

  // This effect ensures navigation only happens after the state is clean.
  React.useEffect(() => {
    if (navigateTo && allowNavigation) {
      navigate(navigateTo);
    }
  }, [navigateTo, allowNavigation, navigate]);


  // --- DUPLICATION LOGIC ---
  // Check if we were sent here with an order to duplicate
  const sourceOrder = location.state?.duplicateOrder as Order | undefined;

  const initialData = React.useMemo(() => {
    if (!sourceOrder) return null;

    // We strip out unique identifiers so it creates a NEW entry
    return {
      ...sourceOrder,
      id: 0, // Reset ID
      orderNumber: '', // Will be generated by DB
      status: OrderStatus.NEW_ORDER, // Reset Status
      createdAt: '', // Reset Date
      updatedAt: '',
      
      // Reset Shipping Specifics (usually different for new orders)
      shippingTrackingNumber: '',
      
      // Reset Financials (Calculated automatically by form)
      amountPaid: 0,
      
      // KEEP: Customer info, Design info, File URLs (Mockups/Production files are reusable for repeats)
    } as Order;
  }, [sourceOrder]);

  const handleSave = async (payload: { current: SaveData; isNew: boolean; changes: any[] }) => {
    setIsSaving(true);
    setError(null);
    
    try {
      // ✅ Extract the actual form data from the payload structure
      const formData = payload.current;
      
      // ✅ LAYER 4: Explicit Type Safety
      // Pass camelCase formData with explicit type casting, let service handle conversion
      
      const sanitizedFormData = {
        // Required String Fields (with type casting to ensure strings)
        customerName: String(formData.customerName || ''),
        customerEmail: String(formData.customerEmail || ''),
        customerPhone: String(formData.customerPhone || ''),
        customerProfileUrl: String(formData.customerProfileUrl || ''),
        
        // Shipping
        shippingAddress: String(formData.shippingAddress || ''),
        shippingCarrier: String(formData.shippingCarrier || ''),
        shippingTrackingNumber: String(formData.shippingTrackingNumber || ''),
        
        // Design & Product
        designName: String(formData.designName || ''),
        patchesQuantity: Number(formData.patchesQuantity) || 0,
        patchesType: String(formData.patchesType || ''),
        designSize: String(formData.designSize || ''),
        designBacking: String(formData.designBacking || ''),
        instructions: String(formData.instructions || ''),
        
        // Financials (with safe number conversion)
        orderAmount: Number(formData.orderAmount) || 0,
        amountPaid: Number(formData.amountPaid) || 0,
        productionCost: Number(formData.productionCost) || 0,
        shippingCost: Number(formData.shippingCost) || 0,
        marketingCost: Number(formData.marketingCost) || 0,
        
        // Status (with explicit fallback)
        status: String(formData.status || OrderStatus.NEW_ORDER),
        
        // Lead & Urgency
        leadSource: String(formData.leadSource || ''),
        isUrgent: Boolean(formData.isUrgent),
        
        // Arrays (ensure they are arrays)
        mockupUrls: Array.isArray(formData.mockupUrls) ? formData.mockupUrls : [],
        productionFileUrls: Array.isArray(formData.productionFileUrls) ? formData.productionFileUrls : [],
        shippingAttachmentUrls: Array.isArray(formData.shippingAttachmentUrls) ? formData.shippingAttachmentUrls : [],
        customerAttachmentUrls: Array.isArray(formData.customerAttachmentUrls) ? formData.customerAttachmentUrls : [],
        
        // Reasons
        reasonCategory: String(formData.reasonCategory || ''),
        reasonDetails: String(formData.reasonDetails || ''),
      };

      // Send the sanitized camelCase payload - service will convert to snake_case
      const newOrder = await createOrder(sanitizedFormData, user?.email || 'unknown');
      
      // ✅ SUCCESS SEQUENCE
      showSuccess(`Order ${newOrder.orderNumber} created successfully!`);
      await queryClient.invalidateQueries({ queryKey: queryKeys.orders.all() });
      await queryClient.invalidateQueries({ queryKey: queryKeys.dashboard.table('', '') });

      setAllowNavigation(true);
      setIsDirty(false);
      setNavigateTo(`/order/${newOrder.orderNumber}/edit`);
      
    } catch (err: any) {
      logger.error('Failed to create order', err);
      const errorMessage = err?.message || (typeof err === 'string' ? err : 'An unknown error occurred. Check the console for details.');
      setError(`Failed to create order: ${errorMessage}`);
      setIsDirty(true);
    } finally {
      setIsSaving(false);
    }
  };

  const onFormChange = React.useCallback(() => {
    console.log('[NewOrderPage] onFormChange called, isSaving:', isSaving);
    if (isSaving) return;
    setIsDirty(true);
    setAllowNavigation(false);
    console.log('[NewOrderPage] Form became dirty');
  }, [isSaving]);

  return (
    <div className="p-6 max-w-7xl mx-auto">
      <div className="mb-6">
        <h2 className="text-3xl font-bold text-white flex items-center gap-3">
          {sourceOrder ? (
            <>
              <Copy className="w-8 h-8 text-blue-400" />
              <span>Repeat Order <span className="text-slate-500 text-lg font-normal">(Copying {sourceOrder.orderNumber})</span></span>
            </>
          ) : (
            "Create New Order"
          )}
        </h2>
        {sourceOrder && (
            <p className="text-slate-400 mt-1 ml-11">
                Details from the previous order have been pre-filled. Please review quantities and costs.
            </p>
        )}
      </div>
      
      <UnsavedChangesModal 
        show={showModal}
        onConfirm={confirmLeave}
        onCancel={cancelLeave}
      />
      
      {error && (
        <div className="mb-6 p-4 bg-red-500/10 border-l-4 border-red-500 text-red-300 rounded-r-lg">
          <h3 className="font-bold">Error</h3>
          <p>{error}</p>
        </div>
      )}
      
      {/* Pass the sanitized 'initialData' to the form to pre-fill it */}
      <OrderForm 
        onSave={handleSave} 
        isSaving={isSaving} 
        onFormChange={onFormChange} 
        initialData={initialData} 
        isNewOrder={true}
      />
    </div>
  );
};

export default NewOrderPage;